# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseBackend' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseBackend
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Firebase/Storage'
  pod 'FBSDKLoginKit'

  target 'FirebaseBackendTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirebaseBackendUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
